version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:

    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:

volumes: